{{- if and .Values.token.create (not .Values.token.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hf-csi.tokenSecretName" . }}
  labels:
    {{- include "hf-csi.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ required "A valid token is required" .Values.token.value | b64enc | quote }}
{{- end }}
