apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.huggingface.co
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
  # Required for Windows support.
  storageCapacity: false
