apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - csi-driver.yaml
  - storageclass.yaml
  - rbac.yaml
  - controller.yaml
  - node.yaml
  - secret.yaml
